sudo: required
services: 
    - docker
before_install:
    - docker build -t haris1822/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true haris1822/react-test npm test
after_success:
    - docker build -t haris1822/multi-client ./client
    - docker build -t haris1822/multi-nginx ./nginx
    - docker build -t haris1822/multi-server ./server
    - docker build -t haris1822/multi-worker ./worker
    # Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images to the docker hub
    - docker push haris1822/multi-client 
    - docker push haris1822/multi-nginx
    - docker push haris1822/multi-server
    - docker push haris1822/multi-worker