sudo: required
language: generic 
services: 
    - docker
before_install:
    - docker build -t "$DOCKER_ID"/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true "$DOCKER_ID"/react-test npm test
after_success:
    - docker build -t "$DOCKER_ID"/multi-client ./client
    - docker build -t "$DOCKER_ID"/multi-nginx ./nginx
    - docker build -t "$DOCKER_ID"/multi-server ./server
    - docker build -t "$DOCKER_ID"/multi-worker ./worker
    # Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images to the docker hub
    - docker push "$DOCKER_ID"/multi-client 
    - docker push "$DOCKER_ID"/multi-nginx
    - docker push "$DOCKER_ID"/multi-server
    - docker push "$DOCKER_ID"/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "multi-container"
    env: "MultiContainer-env"
    bucket_name: "elasticbeanstalk-eu-central-1-211219075453"
    bucket_path: "multi-container"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY